/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 06 23:06:52 GMT 2024
 */

package benchmarks.REVE.average.Eq;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import benchmarks.REVE.average.Eq.newV;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class newV_ESTest extends newV_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      newV newV0 = new newV();
      int[] intArray0 = new int[9];
      intArray0[0] = 305;
      // Undeclared exception!
      try { 
        newV0.average(305, intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 9
         //
         verifyException("benchmarks.REVE.average.Eq.newV", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      newV newV0 = new newV();
      int[] intArray0 = new int[0];
      double double0 = newV0.average((-1), intArray0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      newV newV0 = new newV();
      int[] intArray0 = new int[4];
      intArray0[0] = 1;
      double double0 = newV0.average(1, intArray0);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      newV newV0 = new newV();
      int[] intArray0 = new int[8];
      intArray0[0] = (-128);
      double double0 = newV0.average(1, intArray0);
      assertEquals((-128.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      newV newV0 = new newV();
      // Undeclared exception!
      try { 
        newV0.average(1343, (int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("benchmarks.REVE.average.Eq.newV", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      newV newV0 = new newV();
      int[] intArray0 = new int[50];
      double double0 = newV0.average(0, intArray0);
      assertEquals(0.0, double0, 0.01);
  }
}
